"""docs -- technical documentation management (guides, api, database, reference, tutorials)."""

import datetime
import re

from . import atomic, event_log, fm, paths
from .lock import FileLock

DOCS_DIR = paths.CONTROL_ROOT / "docs"
DOCS_INDEX_MD = DOCS_DIR / "_index.md"

CATEGORIES = ["guides", "api", "database", "reference", "tutorials"]
DOC_STATES = ["draft", "published", "outdated", "deprecated"]

ID_PREFIXES = {
    "guides": "GUIDE",
    "api": "API",
    "database": "DB",
    "reference": "REF",
    "tutorials": "TUT",
}

DOC_TEMPLATES = {}
for cat in CATEGORIES:
    tmpl = DOCS_DIR / cat / "_template.md"
    if tmpl.exists():
        DOC_TEMPLATES[cat] = tmpl.read_text(encoding="utf-8")


def _today():
    return datetime.date.today().isoformat()


def _next_id(categoria):
    prefix = ID_PREFIXES.get(categoria, "DOC")
    cat_dir = DOCS_DIR / categoria
    highest = 0
    if cat_dir.exists():
        for f in cat_dir.iterdir():
            if f.suffix != ".md" or f.name.startswith("_"):
                continue
            m = re.match(rf"^{prefix}-(\d+)\.md$", f.name)
            if m:
                n = int(m.group(1))
                if n > highest:
                    highest = n
    return f"{prefix}-{highest + 1:04d}"


def new_doc(titulo, categoria, tags=None):
    if categoria not in CATEGORIES:
        raise ValueError(f"Categoria invalida: {categoria}. Validas: {CATEGORIES}")
    doc_id = _next_id(categoria)
    cat_dir = DOCS_DIR / categoria
    cat_dir.mkdir(parents=True, exist_ok=True)
    fpath = cat_dir / f"{doc_id}.md"

    content = f"""---
id: {doc_id}
titulo: "{titulo}"
categoria: {categoria}
estado: draft
creado: {_today()}
actualizado: {_today()}
autor: agente
tags: [{tags or ''}]
---

# {titulo}

## Overview

(Describe what this document covers.)

"""

    atomic.write_with_backup(fpath, content)
    reindex()
    event_log.log("doc-created", doc_id, {"titulo": titulo, "categoria": categoria})
    return doc_id, fpath


def list_docs(categoria=None, estado=None):
    items = []
    cats = [categoria] if categoria else CATEGORIES
    for cat in cats:
        cat_dir = DOCS_DIR / cat
        if not cat_dir.exists():
            continue
        for f in sorted(cat_dir.iterdir()):
            if f.suffix != ".md" or f.name.startswith("_"):
                continue
            data, _ = fm.parse(f.read_text(encoding="utf-8"))
            if not data.get("id"):
                continue
            if estado and data.get("estado") != estado:
                continue
            items.append(data)
    return items


def show_doc(doc_id):
    for cat in CATEGORIES:
        fpath = DOCS_DIR / cat / f"{doc_id}.md"
        if fpath.exists():
            return fpath.read_text(encoding="utf-8")
    return None


def set_body(doc_id, new_body):
    for cat in CATEGORIES:
        fpath = DOCS_DIR / cat / f"{doc_id}.md"
        if fpath.exists():
            with FileLock():
                data, _ = fm.parse(fpath.read_text(encoding="utf-8"))
                atomic.write_with_backup(fpath, fm.dump(data, new_body, _key_order(data)))
                reindex()
                event_log.log("doc-updated", doc_id)
                return
    raise ValueError(f"Doc {doc_id} no encontrado")


def touch_estado(doc_id, nuevo_estado):
    if nuevo_estado not in DOC_STATES:
        raise ValueError(f"Estado invalido: {nuevo_estado}. Validos: {DOC_STATES}")
    for cat in CATEGORIES:
        fpath = DOCS_DIR / cat / f"{doc_id}.md"
        if fpath.exists():
            with FileLock():
                data, body = fm.parse(fpath.read_text(encoding="utf-8"))
                data["estado"] = nuevo_estado
                data["actualizado"] = _today()
                atomic.write_with_backup(fpath, fm.dump(data, body, _key_order(data)))
                reindex()
                event_log.log("doc-state-changed", doc_id, {"estado": nuevo_estado})
                return data
    raise ValueError(f"Doc {doc_id} no encontrado")


def _key_order(data):
    preferred = ["id", "titulo", "categoria", "estado", "creado", "actualizado",
                  "autor", "endpoint", "method", "nivel", "duracion_estimada",
                  "dominios", "tags"]
    keys = [k for k in preferred if k in data]
    keys += [k for k in data if k not in preferred]
    return keys


def reindex():
    """Regenerate docs/_index.md from all documentation files."""
    lines = ["# Technical documentation", "",
             "(Generated by `pctl reindex` — do not edit manually)", "",
             "This is the entry point to the project's technical documentation.",
             "Each category groups related documentation files.", "",
             "---", ""]

    counts = {}
    for cat in CATEGORIES:
        docs = list_docs(categoria=cat)
        counts[cat] = len(docs)

        cat_title = cat.capitalize()
        if cat == "api":
            cat_title = "API"
        elif cat == "database":
            cat_title = "Database"

        lines.append(f"## {cat_title}")
        lines.append("")
        lines.append(f"| Doc | Status | Last updated | File |")
        lines.append(f"|---|---|---|---|")
        if not docs:
            lines.append(f"| _(no {cat} yet)_ | | | |")
        else:
            for d in docs:
                did = d.get("id", "?")
                titulo = d.get("titulo", "?")
                estado = d.get("estado", "?")
                actualizado = d.get("actualizado", "?")
                fname = f"{cat}/{did}.md"
                lines.append(f"| **{did}** — {titulo} | {estado} | {actualizado} | {fname} |")
        lines.append("")

    atomic.write(DOCS_INDEX_MD, "\n".join(lines) + "\n")
    return counts
